In [1]:
# Create An array
import numpy as np

In [85]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
# O-Dim array
arr=np.array(23)
print(arr)

23


In [4]:
# 1-Dim array
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
# 2-Dim array
arr=np.array([[1,2,3,4],[5,6,7,9]])
print(arr)

[[1 2 3 4]
 [5 6 7 9]]


In [10]:
# 3-Dim array
arr=np.array([[[1,2,3,4],[5,6,7,9]],[[10,11,12,13],[14,15,16,17]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  9]]

 [[10 11 12 13]
  [14 15 16 17]]]


In [11]:
arr.ndim

3

In [13]:
# Multi-dimensional array
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [14]:
# Accessing an array
my_array=np.array([1,2,3,4])
print(my_array)

[1 2 3 4]


In [15]:
# Upcasting data types
my_array=np.array([1,2,3,'4'])
print(my_array)

['1' '2' '3' '4']


In [16]:
my_array=np.array([1,2,3,4.5])
print(my_array)

[1.  2.  3.  4.5]


In [22]:
# Indexing
my_array=np.array([1,2,3,4])
print(my_array[0])

1


In [18]:
my_array=np.array([1,2,3,4])
print(my_array[0:2])

[1 2]


In [21]:
# Using index in 2-D array
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array[0,2])

3


In [23]:
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array[1,2])

7


In [28]:
# Array vs List

In [29]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1+my_list2}')

LIST:[1, 2, 3, 4, 5, 6, 7, 8]


In [32]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1+my_array2}')

ARRAY:[ 6  8 10 12]


In [35]:
# Adding a single elements
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1[1]+my_list2[1]}')

LIST:8


In [36]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1[1]+my_array2[1]}')

ARRAY:8


In [37]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1-my_list2}')

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [38]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1-my_array2}')

ARRAY:[-4 -4 -4 -4]


In [39]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1*my_array2}')

ARRAY:[ 5 12 21 32]


In [41]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1*my_list2}')

TypeError: can't multiply sequence by non-int of type 'list'

In [43]:
# Copy an array using .copy()
my_array=np.array([1,2,3,4])
array_copy=my_array.copy()
my_array[1]=55
print(f'Original Array: {my_array}')
print(f'Copied Array: {array_copy}')

Original Array: [ 1 55  3  4]
Copied Array: [1 2 3 4]


In [45]:
# View in an array
# Copy an array using .copy()
my_array=np.array([1,2,3,4])
viewed_copy=my_array.view()
my_array[1]=55
print(f'Original Array: {my_array}')
print(f'Viewed Array: {viewed_copy}')

Original Array: [ 1 55  3  4]
Viewed Array: [ 1 55  3  4]


In [46]:
# Iterating an a 2-D array
my_array=np.array([[1,2,3,4],[5,6,7,8]])
for x in my_array:
    print(x)


[1 2 3 4]
[5 6 7 8]


In [47]:
my_array=np.array([[1,2,3,4],[5,6,7,8]])
for x in my_array:
    for i in x:
        print(i)
        
    

1
2
3
4
5
6
7
8


In [48]:
# joining 2 arrays
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(np.concatenate([my_array1,my_array2]))
                    
                    

[1 2 3 4 5 6 7 8]


In [51]:
# 2-D
my_array1=np.array([[1,2,3,4],[5,6,7,8]])
my_array2=np.array([[9,10,11,12],[13,14,15,16]])
print(np.concatenate((my_array1,my_array2)))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [52]:
my_array1=np.array([[1,2,3,4],[5,6,7,8]])
my_array2=np.array([[9,10,11,12],[13,14,15,16]])
print(np.concatenate((my_array1,my_array2),axis=1))

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [53]:
# Joining usin Stack
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(np.stack([my_array1,my_array2]))

[[1 2 3 4]
 [5 6 7 8]]


In [54]:
my_array1=np.array([[1,2,3,4],[5,6,7,8]])
my_array2=np.array([[9,10,11,12],[13,14,15,16]])
print(np.stack((my_array1,my_array2),axis=1))

[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [13 14 15 16]]]


In [57]:
#Splitting an array
my_array=np.array([1,2,3,4])
print(np.array_split(my_array,2))

[array([1, 2]), array([3, 4])]


In [58]:
# Searching for a value in an array using where() returns an index postion
my_array=np.array([1,2,3,4])
print(np.where(my_array==3))

(array([2], dtype=int64),)


In [63]:
# sorting the array using sort
my_array=np.array([10,20,39,45,65,69])
print(np.sort(my_array))

[10 20 39 45 65 69]


In [61]:
# sorting in descending order
my_array=np.array([100,20,39,45,65,69])
print(np.sort(my_array)[::-1])

[100  69  65  45  39  20]


In [65]:
# Filtering an array
my_array=np.array([10,20,39,45,65,69])
filtered_array=my_array>10

In [67]:
filtered_array


array([False,  True,  True,  True,  True,  True])

In [66]:
print(my_array[filtered_array])

[20 39 45 65 69]


In [69]:
my_array=np.array([10,20,39,45,65,69])
my_array[my_array>10]

array([20, 39, 45, 65, 69])

In [74]:
# Create an array of 5x5 (Generates random numbers)
np.random.rand(5,5)

array([[0.27904259, 0.51154522, 0.28602692, 0.87937174, 0.3804372 ],
       [0.9513066 , 0.76050304, 0.44363094, 0.10935914, 0.08907471],
       [0.53150307, 0.22982963, 0.04562691, 0.81796413, 0.65273218],
       [0.05812274, 0.17852761, 0.33943133, 0.95114742, 0.7217784 ],
       [0.22657194, 0.83745124, 0.93490672, 0.83195233, 0.94191835]])

In [78]:
print(my_array.shape)

(6,)


In [79]:
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array.shape)

(2, 4)


In [80]:
# Reshaping an array
my_array=np.array([1,2,3,4])
print(my_array.reshape(2,2))

[[1 2]
 [3 4]]


In [84]:
# Reshaping a multidim into single array
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array.reshape(1,8))

[[1 2 3 4 5 6 7 8]]
